oj_map = {
    "cc": "CodeChef",
    "cf": "CodeForces",
    "gym": "Gym",
    "hdu": "HDU",
    "hr": "HackerRank",
    "kattis": "Kattis",
    "loj": "LightOJ",
    "ojb": "OpenJ_Bailian",
    "poj": "POJ",
    "sgu": "SGU",
    "spoj": "SPOJ",
    "ural": "URAL",
    "uva": "UVA",
    "uvalive": "UVALive",
    "zoj": "ZOJ",
    "eol": "EOlymp",
    "hust": "HUST",
    "scu": "SCU",
    "sgu": "SGU",
    "aizu": "Aizu",
    "atc": "AtCoder"
}
